# Generated by Django 5.2 on 2025-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(default="2025-05-05"),
            preserve_default=False,
        ),
    ]
